---

# common ansible connection
#
# win in clt_asp

# ansible_connection: psrp
# ansible_winrm_server_cert_validation: ignore
# ansible_winrm_message_encryption: always
# ansible_winrm_transport: ntlm
